"""empty message

Revision ID: 213a30c7cb68
Revises: 83249a1ec2a4
Create Date: 2021-12-03 01:30:56.513134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213a30c7cb68'
down_revision = '83249a1ec2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'mana_cost')
    op.drop_column('cards', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('mana_cost', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
