"""empty message

Revision ID: 723f5d0929dd
Revises: 58705985ed5a
Create Date: 2021-11-24 16:59:10.411012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723f5d0929dd'
down_revision = '58705985ed5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decklists', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decklists', 'quantity')
    # ### end Alembic commands ###
