"""empty message

Revision ID: a8d46eb4f615
Revises: 141018dd5cb6
Create Date: 2021-11-29 19:40:17.861369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d46eb4f615'
down_revision = '141018dd5cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'description')
    # ### end Alembic commands ###
