"""empty message

Revision ID: ebb73a52902a
Revises: f218a2cf80d8
Create Date: 2021-11-29 20:08:19.421188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb73a52902a'
down_revision = 'f218a2cf80d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('commander_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'decks', 'cards', ['commander_id'], ['id'])
    op.drop_column('decks', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('format', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'commander_id')
    # ### end Alembic commands ###
