"""empty message

Revision ID: 83249a1ec2a4
Revises: 0b567ceaafe6
Create Date: 2021-12-03 01:30:23.223540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83249a1ec2a4'
down_revision = '0b567ceaafe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('mana_cost', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'mana_cost')
    # ### end Alembic commands ###
