"""empty message

Revision ID: 0b567ceaafe6
Revises: 833937458d9a
Create Date: 2021-12-03 01:29:39.936503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b567ceaafe6'
down_revision = '833937458d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'mana_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('mana_cost', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
