"""empty message

Revision ID: 2d9f98a1408f
Revises: db7d9ee731a9
Create Date: 2021-11-26 14:15:10.523026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9f98a1408f'
down_revision = 'db7d9ee731a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'private')
    # ### end Alembic commands ###
