"""empty message

Revision ID: e1559cae1bfe
Revises: a8d46eb4f615
Create Date: 2021-11-29 19:44:14.567645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1559cae1bfe'
down_revision = 'a8d46eb4f615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decklists', sa.Column('commander', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decklists', 'commander')
    # ### end Alembic commands ###
