"""empty message

Revision ID: 6f1c89e6a883
Revises: 723f5d0929dd
Create Date: 2021-11-24 17:15:06.486754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1c89e6a883'
down_revision = '723f5d0929dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decklists', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decklists', 'id')
    # ### end Alembic commands ###
