"""empty message

Revision ID: 833937458d9a
Revises: ebb73a52902a
Create Date: 2021-12-03 01:24:25.446698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833937458d9a'
down_revision = 'ebb73a52902a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_name_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_name_key', 'cards', ['name'])
    # ### end Alembic commands ###
